#!/bin/bash
# StudyGenie container entrypoint.
#  1. Writes config.php from environment variables.
#  2. Points Apache at $PORT.
#  3. If using the built-in DB, initialises + seeds MariaDB on first boot.
#  4. Hands off to supervisord (MariaDB + Flask + Apache).
set -e

PORT="${PORT:-10000}"
DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-3306}"
DB_USER="${DB_USER:-root}"
DB_PASS="${DB_PASS:-}"
DB_NAME="${DB_NAME:-studygenie_db}"

echo "[entrypoint] PORT=${PORT}  DB_HOST=${DB_HOST}  DB_NAME=${DB_NAME}"

# ── 1. Generate config.php (gitignored; created fresh each boot) ──────────────
cat > /var/www/html/config.php <<PHP
<?php
// Auto-generated by docker/entrypoint.sh from environment variables.
\$server   = getenv('DB_HOST') ?: '127.0.0.1';
\$user     = getenv('DB_USER') ?: 'root';
\$password = getenv('DB_PASS') ?: '';
\$db       = getenv('DB_NAME') ?: 'studygenie_db';
\$port     = (int)(getenv('DB_PORT') ?: 3306);

mysqli_report(MYSQLI_REPORT_OFF);
try {
    \$con = new mysqli(\$server, \$user, \$password, \$db, \$port);
} catch (mysqli_sql_exception \$e) {
    http_response_code(500);
    die("Database connection failed: " . \$e->getMessage());
}
if (\$con->connect_error) { die("Database connection failed: " . \$con->connect_error); }
\$con->set_charset("utf8mb4");

/** Strip the leading unix-timestamp prefix from uploaded filenames. */
function clean_name(string \$filename): string {
    return preg_replace('/^\d{10}_/', '', basename(\$filename));
}
?>
PHP
echo "[entrypoint] wrote config.php"

# ── 2. Apache listens on \$PORT ───────────────────────────────────────────────
echo "Listen ${PORT}" > /etc/apache2/ports.conf
sed -i "s/__PORT__/${PORT}/g" /etc/apache2/sites-available/000-default.conf

# ── 3. Built-in MariaDB: initialise + seed on first boot ─────────────────────
if [ "$DB_HOST" = "127.0.0.1" ] || [ "$DB_HOST" = "localhost" ]; then
    mkdir -p /var/run/mysqld && chown -R mysql:mysql /var/run/mysqld /var/lib/mysql

    if [ ! -d /var/lib/mysql/mysql ]; then
        echo "[entrypoint] initialising MariaDB data dir..."
        mariadb-install-db --user=mysql --datadir=/var/lib/mysql --auth-root-authentication-method=normal >/dev/null 2>&1
    fi

    echo "[entrypoint] starting temporary MariaDB for seeding..."
    mysqld_safe --datadir=/var/lib/mysql --skip-networking=0 &
    for i in $(seq 1 60); do
        if mysqladmin ping --silent 2>/dev/null; then break; fi
        sleep 1
    done

    # Create the DB and allow root to connect over TCP (PHP uses 127.0.0.1, which
    # MariaDB treats as a different host from the default root@localhost socket
    # account -> otherwise "Host '127.0.0.1' is not allowed" / error 1130).
    mysql -u root <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASS}';
CREATE USER IF NOT EXISTS '${DB_USER}'@'%'         IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON *.* TO '${DB_USER}'@'127.0.0.1' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO '${DB_USER}'@'%'         WITH GRANT OPTION;
FLUSH PRIVILEGES;
SQL

    # Seed schema only if the 'users' table is absent (idempotent across restarts
    # when a volume is attached; on free tier the data dir is ephemeral).
    HAS_USERS=$(mysql -u root -N -e "SHOW TABLES FROM \`${DB_NAME}\` LIKE 'users';" 2>/dev/null || true)
    if [ -z "$HAS_USERS" ]; then
        echo "[entrypoint] seeding schema from docker/seed.sql..."
        mysql -u root "${DB_NAME}" < /var/www/html/docker/seed.sql
    else
        echo "[entrypoint] schema already present, skipping seed."
    fi

    echo "[entrypoint] shutting down temporary MariaDB..."
    mysqladmin -u root shutdown
fi

# ── 4. Hand off to supervisord ───────────────────────────────────────────────
echo "[entrypoint] starting supervisord..."
exec supervisord -c /etc/supervisor/conf.d/studygenie.conf
